# lightning.pytorch==2.0.2
# NOTE: null values will use defaults. See https://lightning.ai/docs/pytorch/stable/common/trainer.html.
seed_everything: 42
model:
  model_name: vit_small_patch14_dinov2.lvd142m
  pretrained: true
  im_size: 224
  arc_s: 32.0
  arc_m: 0.5
  lr: 5.0e-05
  sched_steps: 10000
data:
  data_dir: data/til23reid
  batch_size: 128
  num_workers: 16
  rgb_mean:
  - 0.485
  - 0.456
  - 0.406
  rgb_std:
  - 0.229
  - 0.224
  - 0.225
